name: Publish Crates

# This workflow publishes all crates in this repository

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  CACHE_KEY: publish

jobs:
  publish:
    name: Publish Crates
    runs-on: ubuntu-latest
    environment: crates.io
    permissions:
      id-token: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c # v1.15.2
        with:
          cache-key: ${{ env.CACHE_KEY }}
      - name: Install Tools
        run: cargo install cargo-workspaces
      - name: Authenticate using Trusted Publishing
        uses: rust-lang/crates-io-auth-action@b7e9a28eded4986ec6b1fa40eeee8f8f165559ec # v1.0.3
        id: auth
      - name: Publish Crates
        env:
          TOKEN: ${{ steps.auth.outputs.token }}
        run: cargo ws publish --token "$TOKEN" --publish-as-is --skip-published
