name: Test

# This workflow tests the code on multiple platforms.

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CACHE_KEY: test

jobs:
  test:
    strategy:
      matrix:
        include:
          - image: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
          - image: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
          - image: macos-15
            target: aarch64-apple-darwin
          - image: macos-15-intel
            target: x86_64-apple-darwin
          - image: windows-2025
            target: x86_64-pc-windows-msvc
          - image: windows-11-arm
            target: aarch64-pc-windows-msvc
      fail-fast: false
    name: Test ${{ matrix.target }}
    runs-on: ${{ matrix.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Python Toolchain
        # Setup a compatible python-toolchain for the python-bindings
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version-file: "pyproject.toml"
      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@a0b538fa0b742a6aa35d6e2c169b4bd06d225a98 # v1.15.3
        with:
          components: clippy
          cache-key: ${{ env.CACHE_KEY }}-${{ matrix.target}}
          target: ${{ matrix.target }}
          rustflags: "" # Don't fail on warnings
      - name: Run Rust Tests
        run: cargo test --color=always --all-features --target=${{ matrix.target }}
